# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\ninternalpb\"\x19\n\x08LoginReq\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x08LoginRsp\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x42!Z\x1fgame-server/protocol/internalpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037game-server/protocol/internalpb'
  _globals['_LOGINREQ']._serialized_start=27
  _globals['_LOGINREQ']._serialized_end=52
  _globals['_LOGINRSP']._serialized_start=54
  _globals['_LOGINRSP']._serialized_end=83
# @@protoc_insertion_point(module_scope)
